2019-02-23 21:26:22,582 ERROR: Exception on /search [GET] [in c:\microblog\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\microblog\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\microblog\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\microblog\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\microblog\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\microblog\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\microblog\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\microblog\app\main\routes.py", line 145, in search
    posts, total = Post.search(g.search_form.q.data, page, current_app.config['POSTS_PER_PAGE'])
  File "C:\microblog\app\models.py", line 93, in search
    ids, total = query_index(cls.__tablename__, expression, page, per_page)
  File "C:\microblog\app\search.py", line 29, in query_index
    ids = [int(hit['_id']) for hit in search['hits']['hits']]
KeyError: 'hits'
2019-02-23 21:28:33,306 INFO: Microblog startup [in C:\microblog\app\__init__.py:79]
2019-02-23 21:28:40,764 ERROR: Exception on /search [GET] [in c:\microblog\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\microblog\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\microblog\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\microblog\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\microblog\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\microblog\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\microblog\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\microblog\app\main\routes.py", line 145, in search
    posts, total = Post.search(g.search_form.q.data, page, current_app.config['POSTS_PER_PAGE'])
  File "C:\microblog\app\models.py", line 93, in search
    ids, total = query_index(cls.__tablename__, expression, page, per_page)
  File "C:\microblog\app\search.py", line 29, in query_index
    ids = [int(hit['_id']) for hit in search['hits']['hits']]
KeyError: 'hits'
2019-02-23 21:34:15,608 INFO: Microblog startup [in C:\microblog\app\__init__.py:79]
2019-02-23 21:35:42,411 INFO: Microblog startup [in C:\microblog\app\__init__.py:79]
2019-02-23 21:36:15,500 INFO: Microblog startup [in C:\microblog\app\__init__.py:79]
2019-02-23 21:36:21,165 ERROR: Exception on /search [GET] [in c:\microblog\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\microblog\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\microblog\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\microblog\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\microblog\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\microblog\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\microblog\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\microblog\app\main\routes.py", line 145, in search
    posts, total = Post.search(g.search_form.q.data, page, current_app.config['POSTS_PER_PAGE'])
  File "C:\microblog\app\models.py", line 93, in search
    ids, total = query_index(cls.__tablename__, expression, page, per_page)
  File "C:\microblog\app\search.py", line 29, in query_index
    ids = [int(hit['_id']) for hit in search['hits']['hits']]
KeyError: 'hits'
2019-02-23 21:36:33,043 INFO: Microblog startup [in C:\microblog\app\__init__.py:79]
2019-02-23 21:36:48,953 INFO: Microblog startup [in C:\microblog\app\__init__.py:79]
2019-02-23 21:36:57,096 INFO: Microblog startup [in C:\microblog\app\__init__.py:79]
2019-02-23 21:37:13,274 ERROR: Exception on /search [GET] [in c:\microblog\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\microblog\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\microblog\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\microblog\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\microblog\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\microblog\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\microblog\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\microblog\app\main\routes.py", line 145, in search
    posts, total = Post.search(g.search_form.q.data, page, current_app.config['POSTS_PER_PAGE'])
  File "C:\microblog\app\models.py", line 93, in search
    ids, total = query_index(cls.__tablename__, expression, page, per_page)
  File "C:\microblog\app\search.py", line 29, in query_index
    ids = [int(hit['_id']) for hit in search['hits']['hits']]
KeyError: 'hits'
2019-02-23 21:37:55,987 INFO: Microblog startup [in C:\microblog\app\__init__.py:79]
2019-02-23 21:39:02,015 INFO: Microblog startup [in C:\microblog\app\__init__.py:79]
2019-02-23 21:39:27,749 INFO: Microblog startup [in C:\microblog\app\__init__.py:79]
2019-02-23 21:40:17,389 INFO: Microblog startup [in C:\microblog\app\__init__.py:79]
2019-02-23 21:44:23,675 INFO: Microblog startup [in C:\microblog\app\__init__.py:79]
2019-02-23 21:48:20,860 INFO: Microblog startup [in C:\microblog\app\__init__.py:79]
2019-02-23 21:56:48,270 INFO: Microblog startup [in C:\microblog\app\__init__.py:79]
2019-02-23 22:00:40,359 INFO: Microblog startup [in C:\microblog\app\__init__.py:79]
2019-02-23 22:02:55,914 INFO: Microblog startup [in C:\microblog\app\__init__.py:79]
2019-02-23 22:06:20,280 INFO: Microblog startup [in C:\microblog\app\__init__.py:79]
