2019-02-05 03:29:19,920 ERROR: Exception on / [POST] [in c:\microblog\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\microblog\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\microblog\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\microblog\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\microblog\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\microblog\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\microblog\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\microblog\app\routes.py", line 20, in index
    language = translate_client.detect_language(form.post.data)[0]['language']
KeyError: 0
2019-02-05 03:30:01,262 INFO: Microblog startup [in C:\microblog\app\__init__.py:58]
2019-02-05 03:31:26,544 INFO: Microblog startup [in C:\microblog\app\__init__.py:58]
2019-02-05 03:36:02,416 INFO: Microblog startup [in C:\microblog\app\__init__.py:58]
2019-02-05 03:37:20,460 INFO: Microblog startup [in C:\microblog\app\__init__.py:58]
2019-02-05 03:37:57,514 INFO: Microblog startup [in C:\microblog\app\__init__.py:58]
2019-02-05 03:39:34,591 INFO: Microblog startup [in C:\microblog\app\__init__.py:58]
