2019-01-11 05:12:03,862 ERROR: Exception on /follow/dwarkanath [GET] [in c:\microblog\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\microblog\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\microblog\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\microblog\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\microblog\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\microblog\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\microblog\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\microblog\app\routes.py", line 103, in follow
    user = User.query.filter_by(username = username.data).first()
AttributeError: 'str' object has no attribute 'data'
2019-01-11 05:13:54,792 INFO: Microblog startup [in C:\microblog\app\__init__.py:44]
2019-01-11 05:14:03,837 ERROR: Exception on /follow/dwarkanath [GET] [in c:\microblog\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\microblog\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\microblog\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\microblog\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\microblog\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\microblog\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\microblog\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\microblog\app\routes.py", line 103, in follow
    user = User.query.filter_by(username = username.data).first()
AttributeError: 'str' object has no attribute 'data'
2019-01-11 05:15:25,889 INFO: Microblog startup [in C:\microblog\app\__init__.py:44]
